language: python
cache: pip
os: linux
language: python

matrix:
  include:
    - python: 3.8
      env:
      arch: arm64
install:
  - pip install meson ninja

script:
  - meson builddir
  - meson compile -C builddir
  - meson test -C builddir
  - ./run_tests.py
